evap/staff/urls.py
from django.urls import path
from django.views.generic import RedirectView

from evap.staff import views


app_name = "staff"

urlpatterns = [
    path("", views.index, name="index"),

    path("semester/", RedirectView.as_view(url='/staff/', permanent=True)),
    path("semester/create", views.semester_create, name="semester_create"),
    path("semester/<int:semester_id>", views.semester_view, name="semester_view"),
    path("semester/<int:semester_id>/edit", views.semester_edit, name="semester_edit"),
    path("semester/<int:semester_id>/import", views.semester_import, name="semester_import"),
    path("semester/<int:semester_id>/export", views.semester_export, name="semester_export"),
    path("semester/<int:semester_id>/raw_export", views.semester_raw_export, name="semester_raw_export"),
    path("semester/<int:semester_id>/participation_export", views.semester_participation_export, name="semester_participation_export"),
    path("semester/<int:semester_id>/assign", views.semester_questionnaire_assign, name="semester_questionnaire_assign"),
    path("semester/<int:semester_id>/preparation_reminder", views.semester_preparation_reminder, name="semester_preparation_reminder"),
    path("semester/<int:semester_id>/grade_reminder", views.semester_grade_reminder, name="semester_grade_reminder"),
    path("semester/<int:semester_id>/course/create", views.course_create, name="course_create"),
    path("semester/<int:semester_id>/course/<int:course_id>/edit", views.course_edit, name="course_edit"),
    path("semester/<int:semester_id>/evaluation/create", views.evaluation_create, name="evaluation_create"),
    path("semester/<int:semester_id>/evaluation/create/<int:course_id>", views.evaluation_create, name="evaluation_create"),
    path("semester/<int:semester_id>/evaluation/<int:evaluation_id>/edit", views.evaluation_edit, name="evaluation_edit"),
    path("semester/<int:semester_id>/evaluation/<int:evaluation_id>/email", views.evaluation_email, name="evaluation_email"),
    path("semester/<int:semester_id>/evaluation/<int:evaluation_id>/preview", views.evaluation_preview, name="evaluation_preview"),
    path("semester/<int:semester_id>/evaluation/<int:evaluation_id>/person_management", views.evaluation_person_management, name="evaluation_person_management"),
    path("semester/<int:semester_id>/evaluation/<int:evaluation_id>/login_key_export", views.evaluation_login_key_export, name="evaluation_login_key_export"),
    path("semester/<int:semester_id>/evaluation/<int:evaluation_id>/textanswers", views.evaluation_textanswers, name="evaluation_textanswers"),
    path("semester/<int:semester_id>/evaluation/<int:evaluation_id>/textanswer/<uuid:textanswer_id>/edit", views.evaluation_textanswer_edit, name="evaluation_textanswer_edit"),
    path("semester/<int:semester_id>/evaluationoperation", views.semester_evaluation_operation, name="semester_evaluation_operation"),
    path("semester/<int:semester_id>/singleresult/create", views.single_result_create, name="single_result_create"),
    path("semester/<int:semester_id>/singleresult/create/<int:course_id>", views.single_result_create, name="single_result_create"),
    path("semester/<int:semester_id>/responsible/<int:responsible_id>/send_reminder", views.send_reminder, name="send_reminder"),

    path("semester/delete", views.semester_delete, name="semester_delete"),
    path("semester/archive_participations", views.semester_archive_participations, name="semester_archive_participations"),
    path("semester/delete_grade_documents", views.semester_delete_grade_documents, name="semester_delete_grade_documents"),
    path("semester/archive_results", views.semester_archive_results, name="semester_archive_results"),
    path("semester/course_delete", views.course_delete, name="course_delete"),
    path("semester/evaluation_delete", views.evaluation_delete, name="evaluation_delete"),

    path("textanswers/update_publish", views.evaluation_textanswers_update_publish, name="evaluation_textanswers_update_publish"),

    path("questionnaire/", views.questionnaire_index, name="questionnaire_index"),
    path("questionnaire/create", views.questionnaire_create, name="questionnaire_create"),
    path("questionnaire/<int:questionnaire_id>", views.questionnaire_view, name="questionnaire_view"),
    path("questionnaire/<int:questionnaire_id>/edit", views.questionnaire_edit, name="questionnaire_edit"),
    path("questionnaire/<int:questionnaire_id>/new_version", views.questionnaire_new_version, name="questionnaire_new_version"),
    path("questionnaire/<int:questionnaire_id>/copy", views.questionnaire_copy, name="questionnaire_copy"),
    path("questionnaire/delete", views.questionnaire_delete, name="questionnaire_delete"),
    path("questionnaire/update_indices", views.questionnaire_update_indices, name="questionnaire_update_indices"),

    path("degrees/", views.degree_index, name="degree_index"),

    path("course_types/", views.course_type_index, name="course_type_index"),
    path("course_types/merge", views.course_type_merge_selection, name="course_type_merge_selection"),
    path("course_types/<int:main_type_id>/merge/<int:other_type_id>", views.course_type_merge, name="course_type_merge"),

    path("user/", views.user_index, name="user_index"),
    path("user/create", views.user_create, name="user_create"),
    path("user/import", views.user_import, name="user_import"),
    path("user/<int:user_id>/edit", views.user_edit, name="user_edit"),

    path("user/delete", views.user_delete, name="user_delete"),
    path("user/bulk_delete", views.user_bulk_delete, name="user_bulk_delete"),
    path("user/merge", views.user_merge_selection, name="user_merge_selection"),
    path("user/<int:main_user_id>/merge/<int:other_user_id>", views.user_merge, name="user_merge"),

    path("template/", RedirectView.as_view(url='/staff/', permanent=True)),
    path("template/<int:template_id>", views.template_edit, name="template_edit"),

    path("faq/", views.faq_index, name="faq_index"),
    path("faq/<int:section_id>", views.faq_section, name="faq_section"),

    path("download_sample_xls/<str:filename>", views.download_sample_xls, name="download_sample_xls"),

    path("development/components", views.development_components, name="development_components"),
]

evap/staff/templates/staff_evaluation_person_management.html
{% extends 'staff_evaluation_base.html' %}

{% load static %}

{% block content %}
    {{ block.super }}

    {% include 'staff_message_rendering_template.html' with errors=errors warnings=warnings success_messages=success_messages %}

    <div class="row mb-3">
        <div class="col">
            <form id="participant-import-form" method="POST" enctype="multipart/form-data" class="form-vertical h-100">
                {% csrf_token %}
                <div class="card">
                    <div class="card-body h-100">
                        <h4 class="card-title">{% trans 'Import participants' %}</h4>
                        <h6 class="card-subtitle mb-2 text-muted">{% trans 'From Excel file' %}</h6>
                        <p class="card-text">{% trans 'Upload Excel file with participant data' %} (<a href="{% url 'staff:download_sample_xls' 'sample_user.xls' %}">{% trans 'sample file' %}</a>). {% trans 'This will create all containing users.' %}</p>
                        {% include 'bootstrap_form.html' with form=participant_excel_form wide=True %}
                    </div>
                    <div class="card-footer text-center">
                        {% if not participant_test_passed %}
                            <button name="operation" value="test-participants" type="submit" class="btn btn-sm btn-primary form-submit-btn">{% trans 'Upload and test' %}</button>
                        {% else %}
                            <button name="operation" value="test-participants" type="submit" class="btn btn-sm btn-secondary form-submit-btn">{% trans 'Upload and test' %}</button>
                            <div class="form-submit-btn-divider"></div>
                            <button name="operation" value="import-participants" type="submit" class="btn btn-sm btn-primary form-submit-btn">{% trans 'Import previously uploaded file' %}</button>
                        {% endif %}
                    </div>
                </div>
            </form>
        </div>
        <div class="col">
            <form id="participant-copy-form" method="POST" enctype="multipart/form-data" class="form-vertical h-100">
                {% csrf_token %}
                <div class="card h-100">
                    <div class="card-body">
                        <h4 class="card-title">{% trans 'Copy participants' %}</h4>
                    <h6 class="card-subtitle mb-2 text-muted">{% trans 'From other evaluation' %}</h6>
                        <p class="card-text">{% trans 'Copy participants from another evaluation.' %}</p>
                        {% include 'bootstrap_form.html' with form=participant_copy_form wide=True %}
                    </div>
                    <div class="card-footer text-center">
                        <button name="operation" value="copy-participants" type="submit" class="btn btn-sm btn-primary form-submit-btn">{% trans 'Copy participants' %}</button>
                    </div>
                </div>
            </form>
        </div>
    </div>

    <div class="row mb-3">
        <div class="col">
            <form id="contributor-import-form" method="POST" enctype="multipart/form-data" class="form-vertical h-100">
                {% csrf_token %}
                <div class="card h-100">
                    <div class="card-body">
                        <h4 class="card-title">{% trans 'Import contributors' %}</h4>
                        <h6 class="card-subtitle mb-2 text-muted">{% trans 'From Excel file' %}</h6>
                        <p class="card-text">{% trans 'Upload Excel file with contributor data' %} (<a href="{% url 'staff:download_sample_xls' 'sample_user.xls' %}">{% trans 'sample file' %}</a>). {% trans 'This will create all containing users.' %}</p>
                        {% include 'bootstrap_form.html' with form=contributor_excel_form wide=True %}
                    </div>
                    <div class="card-footer text-center">
                        {% if not contributor_test_passed %}
                            <button name="operation" value="test-contributors" type="submit" class="btn btn-sm btn-primary form-submit-btn">{% trans 'Upload and test' %}</button>
                        {% else %}
                            <button name="operation" value="test-contributors" type="submit" class="btn btn-sm btn-secondary form-submit-btn">{% trans 'Upload and test' %}</button>
                            <div class="form-submit-btn-divider"></div>
                            <button name="operation" value="import-contributors" type="submit" class="btn btn-sm btn-primary form-submit-btn">{% trans 'Import previously uploaded file' %}</button>
                        {% endif %}
                    </div>
                </div>
            </form>
        </div>
        <div class="col">
            <form id="contributor-copy-form" method="POST" enctype="multipart/form-data" class="form-vertical h-100">
                {% csrf_token %}
                <div class="card h-100">
                    <div class="card-body">
                        <h4 class="card-title">{% trans 'Copy contributors' %}</h4>
                    <h6 class="card-subtitle mb-2 text-muted">{% trans 'From other evaluation' %}</h6>
                        <p class="card-text">{% trans 'Copy contributors from another evaluation.' %}</p>
                        {% include 'bootstrap_form.html' with form=contributor_copy_form wide=True %}
                    </div>
                    <div class="card-footer text-center">
                        <button name="operation" value="copy-contributors" type="submit" class="btn btn-sm btn-primary form-submit-btn">{% trans 'Copy contributors' %}</button>
                    </div>
                </div>
            </form>
        </div>
    </div>

    <div class="row">
        <div class="col">
            <form id="login-key-export-form" method="POST" class="form-vertical" action="{% url 'staff:evaluation_login_key_export' semester.id evaluation.id %}">
                {% csrf_token %}
                <div class="card">
                    <div class="card-body">
                        <h4 class="card-title">{% trans 'Export login keys' %}</h4>
                        <h6 class="card-subtitle mb-2 text-muted">{% trans 'To CSV file' %}</h6>
                        <p class="card-text">{% trans 'This will create a CSV file containing login keys for all external participants.' %}</p>
                    </div>
                    <div class="card-footer text-center">
                        <button name="operation" value="export-login-keys" type="submit" class="btn btn-sm btn-primary form-submit-btn"
                        {% if not evaluation.has_external_participant %} disabled data-toggle="tooltip" data-placement="top" title="{% trans "This evaluation has no external participants." %}"{% endif %}>
                            {% trans 'Export login keys' %}
                        </button>
                    </div>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

evap/staff/templates/staff_questionnaire_index_list.html
{% if questionnaires %}
    <div class="card collapsible {{ extra_classes }}">
        <div class="card-header">
            <a class="collapse-toggle" data-toggle="collapse" href="#questionnaires-{{ type }}" aria-expanded="false" aria-controls="questionnaires-{{ type }}">
                {% trans headline %}
            </a>
        </div>
        <div class="collapse show" id="questionnaires-{{ type }}">
            <div class="card-body">
                <table class="table table-striped table-vertically-aligned questionnaire-table">
                    <thead>
                        <tr>
                            <th class="movable"></th>
                            <th style="width: 80%">{% trans 'Questionnaire' %}</th>
                            <th style="width: 20%">{% trans 'Actions' %}</th>
                        </tr>
                    </thead>
                    <tbody>
                    {% for questionnaire in questionnaires %}
                        <tr id="questionnaire-row-{{ questionnaire.id }}" class="sortable questionnaire" data-id="{{ questionnaire.id }}" data-index="{{ questionnaire.index }}">
                            <td class="movable"><span class="movable-icon fas fa-arrows-alt-v"></span></td>
                            <td>
                                <strong>{{ questionnaire.name }}</strong>
                                <br />
                                {% blocktrans count questionnaire.questions.all.count as count %}{{ count }} question{% plural %}{{ count }} questions{% endblocktrans %},
                                {% blocktrans count questionnaire.contributions.count as count %}used {{ count }} time{% plural %}used {{ count }} times{% endblocktrans %}
                                {% if questionnaire.obsolete %}<span class="badge badge-warning">{% trans 'obsolete' %}</span>{% endif %}
                                {% if questionnaire.manager_only %}<span class="badge badge-info">{% trans 'managers only' %}</span>{% endif %}
                            </td>
                            <td style="text-align: right;">
                                {% if not questionnaire.obsolete %}
                                    <a href="{% url 'staff:questionnaire_new_version' questionnaire.id %}" class="btn btn-sm btn-light" data-toggle="tooltip" data-placement="top" title="{% trans 'Make obsolete and create new version' %}"><span class="fas fa-clock"></span></a>
                                {% endif %}
                                <a href="{% url 'staff:questionnaire_edit' questionnaire.id %}" class="btn btn-sm btn-light" data-toggle="tooltip" data-placement="top" title="{% trans 'Edit' %}"><span class="fas fa-pencil-alt"></span></a>
                                <a href="{% url 'staff:questionnaire_copy' questionnaire.id %}" class="btn btn-sm btn-light" data-toggle="tooltip" data-placement="top" title="{% trans 'Copy' %}"><span class="fas fa-clone"></span></a>
                                <a href="{% url 'staff:questionnaire_view' questionnaire.id %}" class="btn btn-sm btn-light" data-toggle="tooltip" data-placement="top" title="{% trans 'Preview' %}"><span class="fas fa-eye"></span></a>
                                {% if questionnaire.can_be_deleted_by_manager %}
                                    <button type="button" onclick="deleteQuestionnaireModalShow({{ questionnaire.id }}, '{{ questionnaire.name|escapejs }}');" class="btn btn-sm btn-danger" data-toggle="tooltip" data-placement="top" title="{% trans 'Delete' %}">
                                        <span class="fas fa-trash"></span>
                                    </button>
                                {% else %}
                                    <button type="button" disabled class="btn btn-sm btn-danger" data-toggle="tooltip" data-placement="top"
                                        title="{% trans 'This questionnaire cannot be deleted because it is already in use.' %}">
                                        <span class="fas fa-trash"></span>
                                    </button>
                                {% endif %}
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endif %}

evap/staff/templates/staff_semester_view_evaluation.html
{% load evaluation_filters %}

{% with state=evaluation.state %}


<td>
    {% if request.user.is_manager and not info_only and not semester.participations_are_archived %}
        {% if state == 'new' or state == 'prepared' or state == 'editor_approved' or state == 'approved' or state == 'reviewed' or state == 'published' %}
            <div class="form-check" data-toggle="tooltip" data-placement="top" title="{% trans 'Select for evaluation operation' %}">
                <input class="form-check-input" type="checkbox" name="evaluation" id="evaluation{{ evaluation.id }}" value="{{ evaluation.id }}" />
                <label class="form-check-label" for="evaluation{{ evaluation.id }}"></label>
            </div>
        {% endif %}
    {% endif %}
</td>

{% if state == 'new' %}
    <td class="icon" data-order="0"><span class="fas fa-circle icon-yellow" data-toggle="tooltip" data-placement="top" title="{% trans 'In preparation' %}"></span></td>
{% elif state == 'prepared' %}
    <td class="icon" data-order="2"><span class="far fa-square icon-gray" data-toggle="tooltip" data-placement="top" title="{% trans 'Awaiting editor review' %}"></span></td>
{% elif state == 'editor_approved' %}
    <td class="icon" data-order="1"><span class="far fa-check-square icon-yellow" data-toggle="tooltip" data-placement="top" title="{% trans 'Approved by editor, awaiting manager review' %}"></span></td>
{% elif state == 'approved' or state == 'in_evaluation' or state == 'evaluated' or state == 'reviewed' or state == 'published' %}
    <td class="icon" data-order="3"><span class="far fa-check-square icon-green" data-toggle="tooltip" data-placement="top" title="{% trans 'Approved by manager' %}"></span></td>
{% endif %}

{% if state == 'new' or state == 'prepared' or state == 'editor_approved' %}
    <td class="icon" data-order="1"><span class="fas fa-pause icon-gray" data-toggle="tooltip" data-placement="top" title="{% trans 'Evaluation did not start yet' %}"></span></td>
{% elif state == 'approved' %}
    <td class="icon" data-order="1"><span class="fas fa-pause icon-gray" data-toggle="tooltip" data-placement="top" title="{% trans 'Waiting for evaluation period to start' %}"></span></td>
{% elif state == 'in_evaluation' %}
    <td class="icon" data-order="2"><span class="fas fa-play icon-gray" data-toggle="tooltip" data-placement="top" title="{% trans 'In evaluation' %}"></span></td>
{% elif state == 'evaluated' or state == 'reviewed' or state == 'published' %}
    <td class="icon" data-order="3"><span class="fas fa-stop icon-green" data-toggle="tooltip" data-placement="top" title="{% trans 'Evaluated' %}"></span></td>
{% endif %}

{% if evaluation.num_textanswers == 0 %}
    <td class="icon" data-order="2"><span class="fas fa-comment icon-gray" data-toggle="tooltip" data-placement="top" title="{% trans 'No text answers available' %}"></span></td>
{% elif evaluation.num_textanswers > evaluation.num_reviewed_textanswers %}
    <td class="icon" data-order="1"><span class="fas fa-comment icon-yellow" data-toggle="tooltip" data-placement="top" title="{% trans 'Text answers awaiting review' %}"></span></td>
{% else %}
    <td class="icon" data-order="3"><span class="fas fa-comment icon-green" data-toggle="tooltip" data-placement="top" title="{% trans 'Text answers reviewed' %}"></span></td>
{% endif %}

{% if state == 'new' or state == 'prepared' or state == 'editor_approved' or state == 'approved' or state == 'in_evaluation' or state == 'evaluated' %}
    <td class="icon" data-order="2"><span class="fas fa-chart-bar icon-gray" data-toggle="tooltip" data-placement="top" title="{% trans 'Evaluation not finished' %}"></span></td>
{% elif state == 'reviewed' %}
    {% if evaluation.is_single_result or evaluation.course.final_grade_documents or evaluation.course.gets_no_grade_documents or not evaluation.course.is_graded %}
        <td class="icon text-center" data-order="0"><span class="fas fa-chart-bar icon-red" data-toggle="tooltip" data-placement="top" title="{% trans 'Results not yet published although they probably could be' %}"></span></td>
    {% else %}
        <td class="icon text-center" data-order="1"><span class="fas fa-chart-bar icon-yellow" data-toggle="tooltip" data-placement="top" title="{% trans 'Results not yet published' %}"></span></td>
    {% endif %}
{% elif state == 'published' %}
    <td class="icon" data-order="3"><span class="fas fa-chart-bar icon-green" data-toggle="tooltip" data-placement="top" title="{% trans 'Results published' %}"></span></td>
{% endif %}

<td style="width: {% if info_only %}51%{% else %}42%{% endif %}" data-order="{{ evaluation.full_name }}">
    <div>
    {% if not info_only and request.user.is_manager %}
        <a href="{% url 'staff:evaluation_edit' semester.id evaluation.id %}">{{ evaluation.full_name }}</a>
        <a class="small no-underline" href="{% url 'staff:course_edit' semester.id evaluation.course.id %}" data-toggle="tooltip" data-placement="right" title="{% trans 'Edit course' %}">
            <span class="fas fa-chalkboard-teacher"></span>
        </a>
    {% else %}
        {{ evaluation.full_name }}
    {% endif %}
    </div>
    <div class="font-italic">
        {{ evaluation.course.responsibles_names }}
        {% if info_only or not request.user.is_manager or state == 'in_evaluation' or state == 'evaluated' or state == 'reviewed' or state == 'published' %}
            <span class="small" data-toggle="tooltip" data-placement="right" title="{% trans 'Number of contributors' %}">
                ({{ evaluation.num_contributors }} <span class="fas fa-graduation-cap"></span>)
            </span>
        {% else %}
            <a class="small no-underline" href="{% url 'staff:evaluation_person_management' semester.id evaluation.id %}" data-toggle="tooltip" data-placement="right" title="{% trans 'Manage contributors' %}">
                ({{ evaluation.num_contributors }} <span class="fas fa-graduation-cap"></span>)
            </a>
        {% endif %}
    </div>
    {% include 'evaluation_badges.html' with mode='manager' %}

    {% if state == 'new' or state == 'prepared' or state == 'editor_approved' %}
        {% if not evaluation.all_contributions_have_questionnaires %}
            {% if not evaluation.general_contribution_has_questionnaires %}
                <span class="badge badge-danger">{% trans 'Evaluation has no questionnaires' %}</span>
            {% else %}
                <span class="badge badge-warning">{% trans 'Not all contributors have questionnaires' %}</span>
            {% endif %}
        {% endif %}
    {% endif %}
</td>
<td style="width: 22%" data-order="{{ evaluation|ordering_index }}">
    {% include 'staff_evaluation_evaluation_period.html' %}
</td>
{% if state == 'in_evaluation' or state == 'evaluated' or state == 'reviewed' or state == 'published' %}
    {% if not evaluation.is_single_result %}
        <td style="width: 20%" class="multi-progress-bar">
            {% if evaluation.can_publish_average_grade %}
                <span data-toggle="tooltip" data-placement="left" title="{% trans 'Number of voters' %}">
                    {% include 'progress_bar.html' with done=evaluation.num_voters total=evaluation.num_participants icon='user' %}
                </span>
            {% else %}
                <span data-toggle="tooltip" data-placement="left" title="{% trans 'Not enough voters to publish average grade' %}">
                    {% include 'progress_bar.html' with done=evaluation.num_voters total=evaluation.num_participants icon='user' warning=True %}
                </span>
            {% endif %}
            {% if evaluation.num_textanswers > 0 and state != 'published' and not info_only %}
                <a class="no-underline" href="{% url 'staff:evaluation_textanswers' semester.id evaluation.id %}" data-toggle="tooltip" data-placement="left" title="{% trans 'Review text answers' %}">
                    {% include 'progress_bar.html' with done=evaluation.num_reviewed_textanswers total=evaluation.num_textanswers icon='comment' %}
                </a>
            {% elif info_only %}
                <span data-toggle="tooltip" data-placement="left" title="{% trans 'Number of text answers' %}">
                    {% include 'progress_bar.html' with done=evaluation.num_reviewed_textanswers total=evaluation.num_textanswers icon='comment' %}
                </span>
            {% else %}
                <span data-toggle="tooltip" data-placement="left" title="{% trans 'Number of text answers' %}">
                    <span class="fas fa-comment"></span> {{ evaluation.num_textanswers }}
                </span>
                <br />
            {% endif %}
            {% if evaluation.course.is_graded %}
                {% if info_only or not request.user.is_manager %}
                    <span data-toggle="tooltip" data-placement="left" title="{% trans 'Grade documents (Midterm, Final)' %}">
                        <span class="fas fa-file"></span>
                        {% blocktrans with midterm=evaluation.midterm_grade_documents_count final=evaluation.final_grade_documents_count %}M: {{ midterm }}, F: {{ final }}{% endblocktrans %}
                    </span>
                {% else %}
                    <a href="{% url 'grades:course_view' semester.id evaluation.course.id %}" data-toggle="tooltip" data-placement="left" title="{% trans 'Grade documents (Midterm, Final)' %}">
                        <span class="fas fa-file"></span>
                        {% blocktrans with midterm=evaluation.midterm_grade_documents_count final=evaluation.final_grade_documents_count %}M: {{ midterm }}, F: {{ final }}{% endblocktrans %}
                    </a>
                {% endif %}
                {% if evaluation.final_grade_documents_count %}
                    <span class="fas fa-check" data-toggle="tooltip" data-placement="top" title="{% trans 'Final grades have been uploaded' %}"></span>
                {% elif evaluation.course.gets_no_grade_documents %}
                    <span class="fas fa-check" data-toggle="tooltip" data-placement="top" title="{% trans 'It was confirmed that final grades have been submitted' %}"></span>
                {% endif %}
            {% endif %}
        </td>
    {% else %}
        <td style="width: 20%">
            <span data-toggle="tooltip" data-placement="left" title="{% trans 'Number of voters' %}">
                <span class="fas fa-user"></span> {{ evaluation.num_voters }}
            </span>
        </td>
    {% endif %}
{% elif info_only or not request.user.is_manager %}
    <td style="width: 20%">
        <span data-toggle="tooltip" data-placement="top" title="{% trans 'Number of participants' %}">
            <span class="fas fa-user"></span> {{ evaluation.num_participants }}
        </span>
    </td>
{% else %}
    <td style="width: 20%">
        <a class="no-underline" href="{% url 'staff:evaluation_person_management' semester.id evaluation.id %}" data-toggle="tooltip" data-placement="left" title="{% trans 'Manage participants' %}">
            <span class="fas fa-user"></span> {{ evaluation.num_participants }}
        </a>
    </td>
{% endif %}
{% if not info_only %}
    <td style="width: 16%">
        {% if request.user.is_manager %}
            <a href="{% url 'staff:evaluation_email' semester.id evaluation.id %}" class="btn btn-sm btn-light" data-toggle="tooltip" data-placement="top" title="{% trans 'Send email' %}">
                <span class="fas fa-envelope" aria-hidden="true"></span>
            </a>
        {% endif %}
        {% if state == 'new' or state == 'prepared' or state == 'editor_approved' or state == 'approved' %}
            <a href="{% url 'staff:evaluation_preview' semester.id evaluation.id %}" class="btn btn-sm btn-light" data-toggle="tooltip" data-placement="top" title="{% trans 'Preview' %}">
                <span class="fas fa-eye" aria-hidden="true"></span>
            </a>
        {% elif state == 'in_evaluation' or state == 'evaluated' or state == 'reviewed' and evaluation|can_results_page_be_seen_by:request.user %}
            <a href="{% url 'results:evaluation_detail' semester.id evaluation.id %}" class="btn btn-sm btn-light" data-toggle="tooltip" data-placement="top" title="{% trans 'Preview results' %}">
                <span class="fas fa-chart-bar" aria-hidden="true"></span>
            </a>
        {% elif state == 'published' and evaluation|can_results_page_be_seen_by:request.user %}
            <a href="{% url 'results:evaluation_detail' semester.id evaluation.id %}" class="btn btn-sm btn-light" data-toggle="tooltip" data-placement="top" title="{% trans 'Results' %}">
                <span class="fas fa-chart-bar" aria-hidden="true"></span>
            </a>
        {% endif %}
        {% if request.user.is_manager and evaluation.can_be_deleted_by_manager %}
            <button type="button" onclick="deleteEvaluationModalShow({{ evaluation.id }}, '{{ evaluation.full_name|escapejs }}');" class="btn btn-sm btn-outline-danger" data-toggle="tooltip" data-placement="top" title="{% trans 'Delete' %}">
                <span class="fas fa-trash" aria-hidden="true"></span>
            </button>
        {% endif %}
    </td>
{% endif %}

{% endwith %}